// Generated by gencpp from file kubot_msgs/BatteryVoltage.msg
// DO NOT EDIT!


#ifndef KUBOT_MSGS_MESSAGE_BATTERYVOLTAGE_H
#define KUBOT_MSGS_MESSAGE_BATTERYVOLTAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kubot_msgs
{
template <class ContainerAllocator>
struct BatteryVoltage_
{
  typedef BatteryVoltage_<ContainerAllocator> Type;

  BatteryVoltage_()
    : header()
    , batterymeter(false)
    , battery_voltage(0.0)  {
    }
  BatteryVoltage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , batterymeter(false)
    , battery_voltage(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _batterymeter_type;
  _batterymeter_type batterymeter;

   typedef float _battery_voltage_type;
  _battery_voltage_type battery_voltage;





  typedef boost::shared_ptr< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryVoltage_

typedef ::kubot_msgs::BatteryVoltage_<std::allocator<void> > BatteryVoltage;

typedef boost::shared_ptr< ::kubot_msgs::BatteryVoltage > BatteryVoltagePtr;
typedef boost::shared_ptr< ::kubot_msgs::BatteryVoltage const> BatteryVoltageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kubot_msgs::BatteryVoltage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kubot_msgs::BatteryVoltage_<ContainerAllocator1> & lhs, const ::kubot_msgs::BatteryVoltage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.batterymeter == rhs.batterymeter &&
    lhs.battery_voltage == rhs.battery_voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kubot_msgs::BatteryVoltage_<ContainerAllocator1> & lhs, const ::kubot_msgs::BatteryVoltage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kubot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d70f523bb615ef811f67251c32690e21";
  }

  static const char* value(const ::kubot_msgs::BatteryVoltage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd70f523bb615ef81ULL;
  static const uint64_t static_value2 = 0x1f67251c32690e21ULL;
};

template<class ContainerAllocator>
struct DataType< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kubot_msgs/BatteryVoltage";
  }

  static const char* value(const ::kubot_msgs::BatteryVoltage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool batterymeter\n"
"float32  battery_voltage\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kubot_msgs::BatteryVoltage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.batterymeter);
      stream.next(m.battery_voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryVoltage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kubot_msgs::BatteryVoltage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kubot_msgs::BatteryVoltage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "batterymeter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.batterymeter);
    s << indent << "battery_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.battery_voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUBOT_MSGS_MESSAGE_BATTERYVOLTAGE_H
